#!/bin/bash

ln -s /cache/node_modules $(pwd)/node_modules
docker run --rm -t --privileged -v $(pwd):/app -v /cache/node_modules:/cache/node_modules -v /var/run/docker.sock:/var/run/docker.sock:rw -v /.dockercfg:/.dockercfg:ro --volumes-from builder_cache tutum/builder $1
